"""
End-to-End RAG Pipeline module for the Enverus RAG system.

Orchestrates semantic retrieval over indexed document chunks, constructs
grounded evidence prompts, and invokes local LLM generation via Ollama/Qwen.
"""

from dataclasses import dataclass
import time
from typing import Any, Dict, List, Optional, Union
from dotenv import load_dotenv

from src.generator import (
    DEFAULT_SYSTEM_PROMPT,
    LLMGenerator,
    build_rag_prompt,
    get_generator,
)
from src.retriever import (
    RetrievalResult,
    SemanticRetriever,
    get_retriever,
)
from src.safety import (
    INSUFFICIENT_EVIDENCE_RESPONSE,
    check_entity_sufficiency,
    validate_rag_grounding,
)

load_dotenv()


@dataclass(frozen=True)
class RAGSource:
    """
    Structured representation of a retrieved evidence chunk attached to a RAG response.

    Attributes:
        rank: 1-indexed retrieval position (Rank 1 is the most relevant match).
        chunk_id: Unique identifier of the document chunk.
        page_number: 1-indexed source document page.
        section: Source section or appendix heading (or None).
        score: Cosine similarity score (1.0 - cosine_distance).
        distance: Raw ChromaDB cosine distance.
        text: Original unedited chunk text provided to the model.
    """
    rank: int
    chunk_id: str
    page_number: int
    section: Optional[str]
    score: float
    distance: float
    text: str

    def to_dict(self) -> Dict[str, Any]:
        """Converts the source record to a serializable dictionary."""
        return {
            "rank": self.rank,
            "chunk_id": self.chunk_id,
            "page_number": self.page_number,
            "section": self.section,
            "score": self.score,
            "distance": self.distance,
            "text": self.text,
        }

    @classmethod
    def from_retrieval_result(cls, r: RetrievalResult) -> "RAGSource":
        """Factory method to convert a RetrievalResult into a RAGSource."""
        return cls(
            rank=r.rank,
            chunk_id=r.chunk_id,
            page_number=r.page_number,
            section=r.section,
            score=r.score,
            distance=r.distance,
            text=r.text,
        )


@dataclass(frozen=True)
class RAGResponse:
    """
    Structured response returned by the end-to-end RAG pipeline.

    Attributes:
        question: The user input query.
        answer: The text generated by the local LLM.
        sources: List of RAGSource objects provided to the model as evidence.
        model: Identifier of the generating LLM model.
        top_k: Number of retrieved chunks requested/provided.
        latency: Total round-trip generation latency in seconds (if measured).
    """
    question: str
    answer: str
    sources: List[RAGSource]
    model: str
    top_k: int
    latency: Optional[float] = None
    safety_triggered: bool = False
    safety_reason: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Converts the complete RAG response to a serializable dictionary."""
        return {
            "question": self.question,
            "answer": self.answer,
            "sources": [s.to_dict() for s in self.sources],
            "model": self.model,
            "top_k": self.top_k,
            "latency": self.latency,
            "safety_triggered": self.safety_triggered,
            "safety_reason": self.safety_reason,
        }


class RAGPipeline:
    """
    End-to-end orchestration pipeline for retrieval-augmented generation.

    Coordinates SemanticRetriever for evidence selection, prompt assembly via
    build_rag_prompt, and factual generation via LLMGenerator.
    """

    def __init__(
        self,
        retriever: Optional[SemanticRetriever] = None,
        generator: Optional[LLMGenerator] = None,
        default_top_k: int = 5,
    ):
        """
        Initializes the RAG pipeline with retriever and generator components.

        Args:
            retriever: SemanticRetriever instance for chunk retrieval.
                       Defaults to get_retriever().
            generator: LLMGenerator instance for local inference.
                       Defaults to get_generator().
            default_top_k: Default number of chunks to retrieve if unspecified.
        """
        self._retriever = retriever
        self._generator = generator
        self.default_top_k = default_top_k

    @property
    def retriever(self) -> SemanticRetriever:
        """Lazily obtains the semantic retriever instance."""
        if self._retriever is None:
            self._retriever = get_retriever()
        return self._retriever

    @property
    def generator(self) -> LLMGenerator:
        """Lazily obtains the LLM generator instance."""
        if self._generator is None:
            self._generator = get_generator()
        return self._generator

    def answer(
        self,
        question: str,
        top_k: Optional[int] = None,
        system_prompt: Optional[str] = None,
    ) -> RAGResponse:
        """
        Executes the full RAG workflow for a user question.

        1. Validates the question.
        2. Retrieves the top_k relevant evidence chunks using SemanticRetriever.
        3. Formats evidence and question into a grounded prompt via build_rag_prompt().
        4. Generates a factual response using LLMGenerator.
        5. Packages answer and full evidence sources into a structured RAGResponse.

        Args:
            question: The user query string.
            top_k: Number of chunks to retrieve (defaults to self.default_top_k).
            system_prompt: Optional override for the grounding system prompt.

        Returns:
            A RAGResponse containing the question, answer, and all retrieved sources.

        Raises:
            TypeError: If question is not a string.
            ValueError: If question is empty or whitespace-only.
            OllamaConnectionError: If Ollama server is unreachable.
            OllamaModelNotFoundError: If configured model is missing.
            OllamaTimeoutError: If generation exceeds timeout.
            OllamaResponseError: If generation returns malformed response.
        """
        # 1. Validate question
        if not isinstance(question, str):
            raise TypeError(f"Question must be a string, got {type(question).__name__}.")
        cleaned_question = question.strip()
        if not cleaned_question:
            raise ValueError("Question cannot be empty or whitespace-only.")

        k = top_k if top_k is not None else self.default_top_k

        # 2. Retrieve relevant evidence chunks
        retrieval_results: List[RetrievalResult] = self.retriever.retrieve(
            query=cleaned_question,
            top_k=k,
        )

        # 3. Convert to traceable RAGSource objects
        sources: List[RAGSource] = [
            RAGSource.from_retrieval_result(r) for r in retrieval_results
        ]
        evidence_texts = [s.text for s in sources]

        # 4. Stage 1 Safety Check: Pre-generation entity / identifier sufficiency
        is_sufficient, entity_reason = check_entity_sufficiency(cleaned_question, evidence_texts)
        if not is_sufficient:
            return RAGResponse(
                question=cleaned_question,
                answer=INSUFFICIENT_EVIDENCE_RESPONSE,
                sources=sources,
                model=self.generator.model,
                top_k=len(sources),
                latency=0.0,
                safety_triggered=True,
                safety_reason=entity_reason,
            )

        # 5. Construct grounded prompt with exact original chunk text
        prompt = build_rag_prompt(
            question=cleaned_question,
            evidence=retrieval_results,
        )

        # 6. Execute generation and measure total latency
        start_time = time.perf_counter()
        raw_answer = self.generator.generate(
            prompt=prompt,
            system_prompt=system_prompt if system_prompt is not None else DEFAULT_SYSTEM_PROMPT,
        )
        latency = time.perf_counter() - start_time

        # 7. Stage 2 Safety Check: Post-generation grounding & numerical safety validation
        final_answer, safety_triggered, safety_reason = validate_rag_grounding(
            question=cleaned_question,
            raw_answer=raw_answer,
            evidence_texts=evidence_texts,
        )

        # 8. Assemble complete response
        return RAGResponse(
            question=cleaned_question,
            answer=final_answer,
            sources=sources,
            model=self.generator.model,
            top_k=len(sources),
            latency=latency,
            safety_triggered=safety_triggered,
            safety_reason=safety_reason,
        )


def get_rag_pipeline(
    retriever: Optional[SemanticRetriever] = None,
    generator: Optional[LLMGenerator] = None,
    default_top_k: int = 5,
) -> RAGPipeline:
    """Factory helper to obtain a RAGPipeline instance."""
    return RAGPipeline(
        retriever=retriever,
        generator=generator,
        default_top_k=default_top_k,
    )
