"""
Semantic retrieval module for the Enverus RAG pipeline.

Executes dense semantic retrieval over embedded document chunks stored in ChromaDB
using query vector embeddings generated by SentenceTransformers.
"""

from dataclasses import dataclass
import os
from typing import Any, Dict, List, Optional
from dotenv import load_dotenv

from src.embeddings import EmbeddingManager
from src.vector_store import VectorStore, get_vector_store

load_dotenv()

DEFAULT_TOP_K = int(os.getenv("DEFAULT_TOP_K", "5"))


@dataclass(frozen=True)
class RetrievalResult:
    """
    Structured representation of an individual retrieval result chunk.

    Attributes:
        rank: 1-indexed retrieval ranking based on similarity (1 is the top match).
        chunk_id: Unique document chunk identifier (e.g., 'chunk_p06_001').
        text: Original chunk text preserved from the document.
        page_number: 1-indexed source document page number.
        section: Source section or appendix heading (or None if unavailable).
        score: Cosine similarity score derived as (1.0 - distance).
               Ranges from -1.0 to 1.0 (with 1.0 indicating identical orientation).
        distance: Raw cosine distance returned by ChromaDB (hnsw:space: cosine).
                  Ranges from 0.0 to 2.0 (with 0.0 indicating identical orientation).
    """
    rank: int
    chunk_id: str
    text: str
    page_number: int
    section: Optional[str]
    score: float
    distance: float

    def to_dict(self) -> Dict[str, Any]:
        """Converts the retrieval result to a dictionary representation."""
        return {
            "rank": self.rank,
            "chunk_id": self.chunk_id,
            "text": self.text,
            "page_number": self.page_number,
            "section": self.section,
            "score": self.score,
            "distance": self.distance,
        }


class SemanticRetriever:
    """
    Baseline dense semantic retriever.

    Coordinates query embedding generation via EmbeddingManager and nearest-neighbor
    vector search via ChromaDB VectorStore.
    """

    def __init__(
        self,
        vector_store: Optional[VectorStore] = None,
        embedding_manager: Optional[EmbeddingManager] = None,
        default_top_k: int = DEFAULT_TOP_K,
    ):
        """
        Initializes the retriever with vector store and embedding dependencies.

        Args:
            vector_store: VectorStore instance for ChromaDB index queries.
                          Defaults to get_vector_store().
            embedding_manager: EmbeddingManager instance for encoding queries.
                               Defaults to EmbeddingManager().
            default_top_k: Default number of top results to return if not specified in retrieve().
        """
        self._vector_store = vector_store
        self._embedding_manager = embedding_manager
        self.default_top_k = default_top_k

    @property
    def vector_store(self) -> VectorStore:
        """Lazily obtains the vector store instance."""
        if self._vector_store is None:
            self._vector_store = get_vector_store()
        return self._vector_store

    @property
    def embedding_manager(self) -> EmbeddingManager:
        """Lazily obtains the embedding manager instance."""
        if self._embedding_manager is None:
            self._embedding_manager = EmbeddingManager()
        return self._embedding_manager

    def retrieve(self, query: str, top_k: Optional[int] = None) -> List[RetrievalResult]:
        """
        Retrieves the top_k most semantically relevant chunks for a user query.

        Args:
            query: The user search query string.
            top_k: Number of chunks to retrieve. Defaults to self.default_top_k (5).

        Returns:
            List of RetrievalResult objects ordered by rank (nearest distance first).

        Raises:
            TypeError: If query is not a string or top_k is not an integer.
            ValueError: If query is empty/whitespace, top_k is non-positive,
                        collection is empty, or top_k exceeds collection size.
        """
        # 1. Validate query
        if not isinstance(query, str):
            raise TypeError(f"Query must be a string, got {type(query).__name__}.")
        cleaned_query = query.strip()
        if not cleaned_query:
            raise ValueError("Query cannot be empty or whitespace-only.")

        # 2. Determine and validate top_k
        k = top_k if top_k is not None else self.default_top_k
        if isinstance(k, bool) or not isinstance(k, int):
            raise TypeError(f"top_k must be an integer, got {type(k).__name__}.")
        if k <= 0:
            raise ValueError(f"top_k must be a positive integer, got {k}.")

        # 3. Validate collection state and boundary
        collection_count = self.vector_store.count()
        if collection_count == 0:
            raise ValueError("Cannot retrieve from an empty vector collection (0 records).")
        if k > collection_count:
            raise ValueError(
                f"Requested top_k ({k}) exceeds total collection size ({collection_count})."
            )

        # 4. Generate query embedding vector using existing EmbeddingManager
        query_vector = self.embedding_manager.embed_query(cleaned_query)

        # 5. Query ChromaDB collection with cosine distance
        query_response = self.vector_store.collection.query(
            query_embeddings=[query_vector],
            n_results=k,
            include=["documents", "metadatas", "distances"],
        )

        # 6. Unpack ChromaDB response into structured RetrievalResult items
        ids = query_response.get("ids", [[]])[0]
        documents = query_response.get("documents", [[]])[0]
        metadatas = query_response.get("metadatas", [[]])[0]
        distances = query_response.get("distances", [[]])[0]

        results: List[RetrievalResult] = []
        for idx in range(len(ids)):
            chunk_id = ids[idx]
            text = documents[idx] if idx < len(documents) else ""
            meta = metadatas[idx] if idx < len(metadatas) else {}
            dist = float(distances[idx]) if idx < len(distances) else 0.0

            # Cosine similarity for normalized embeddings: similarity = 1.0 - cosine_distance
            similarity_score = 1.0 - dist

            # Extract metadata safely
            page_number = int(meta.get("page_number", 0))
            raw_section = meta.get("section", "")
            section = raw_section if raw_section != "" else None

            results.append(
                RetrievalResult(
                    rank=idx + 1,
                    chunk_id=chunk_id,
                    text=text,
                    page_number=page_number,
                    section=section,
                    score=similarity_score,
                    distance=dist,
                )
            )

        return results


def get_retriever(
    vector_store: Optional[VectorStore] = None,
    embedding_manager: Optional[EmbeddingManager] = None,
    default_top_k: int = DEFAULT_TOP_K,
) -> SemanticRetriever:
    """Factory helper to obtain a SemanticRetriever instance."""
    return SemanticRetriever(
        vector_store=vector_store,
        embedding_manager=embedding_manager,
        default_top_k=default_top_k,
    )


def retrieve(
    query: str,
    top_k: Optional[int] = None,
    retriever: Optional[SemanticRetriever] = None,
) -> List[RetrievalResult]:
    """
    Convenience function for semantic retrieval.

    Args:
        query: User search query.
        top_k: Number of results to retrieve (default: 5).
        retriever: Optional retriever instance.

    Returns:
        List of RetrievalResult objects.
    """
    active_retriever = retriever or get_retriever()
    return active_retriever.retrieve(query=query, top_k=top_k)
